Feature/setup
Salimer/react-to-do-list pull request #1
Opened 2023-06-05 13:49 UTC by Salimer

2023-06-06 05:08 UTC, Mar12358 requested changes
## Hi @Salimer !
You did a great job so far, but there are still some required sections missing.

### Highlights 💯 
✔️ The repo is professional according to the [basic rules]
✔️ Descriptive README file.
✔️ Meaningful Commit history.
✔️ Professional PR
✔️ Check linters
✔️ Descriptive Branch name.
✔️ App works as expected.
✔️ App runs successfully.
✔️ Hooks (useEffect, useState)
✔️ Props and state usage.
✔️ Good job using Vite.
✔️ Good quality code (DRY, KISS, and YAGNI).
![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)
## Required Changes ♻️
You did a great effort on your app functionality and its style, but there are still some required concepts on the tutorial that are not implemented on your project. Please check the following checklist and the comments below:

- [ ] ❌ Gitflow [OPTIONAL] Remember to have a dev branch parallel to main, and the feature branch that you actually code and then compare to develop branch with your PR. Remember using it further on.
 
- [ ] I kindly suggest adding routing with React Router, since it's one of the required sections of the tutorial. (Part 9)

- [ ] Please, consider adding the navbar, since it is a required section in the tutorioal. This would lead to implement its features as well, such as Login/logout components, Home/About/Login/Profile pages, routing in general, limiting edit button access and profile preview if not logged in.

2023-06-06 05:08 UTC, Mar12358 commented on murple_logo.png
Nice Logo! 🥇

2023-06-06 05:08 UTC, Mar12358 commented on README.md
Very Good Job on your Documentation, Congratulations! 💯

2023-06-06 05:08 UTC, Mar12358 commented on src/components/InputTodo.jsx
> +  }
Good Job!

2023-06-06 05:08 UTC, Mar12358 commented on src/components/InputTodo.jsx
> +import { FaPlusCircle } from "react-icons/fa";
Good Job implementing react-icons! 🥇

2023-06-06 08:35 UTC, Salimer commented
Thank you @Mar12358 for the thorough review. By mistake I started this pull request to the wrong branch 'main' when I should make it to the 'development' branch. I will address the suggested changes in another pull request. Please review my new [Pull Request](https://github.com/Salimer/react-to-do-list/pull/2)

2023-06-06 15:29 UTC, Mar12358 approved these changes
Hi @Salimer 👋,

## Status: Approved 🟢   
![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
✔️ The repo is professional according to the [basic rules]
✔️ Descriptive README file.
✔️ Meaningful Commit history.
✔️ Professional PR
✔️ Check linters
✔️ Descriptive Branch name.
✔️ App works as expected.
✔️ App runs successfully.
✔️ Hooks (useEffect, useState)
✔️ Props and state usage.
✔️ Good job using Vite.
✔️ Good quality code (DRY, KISS, and YAGNI).
✔️ **Good Job implemented the required changes**
✔️ Routing
✔️ Add navbar
✔️ GitFlow

### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Mar12358 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-07 11:09 UTC, Salimer commented
Thank you @Mar12358 for the thorough review 🥳

2024-09-08 09:55 UTC, closed without merging